# Generated by Django 3.0.8 on 2020-07-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='First name', max_length=25)),
                ('last_name', models.CharField(default='Last name', max_length=30)),
                ('date_of_birth', models.DateField(default='2000-12-12')),
                ('age', models.IntegerField(default='0')),
                ('pesel', models.CharField(default='0', max_length=11)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Quest2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy', models.BooleanField(default=False)),
                ('cigarettes', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('drugs', models.CharField(blank=True, max_length=100, null=True)),
                ('injury', models.CharField(blank=True, max_length=200, null=True)),
                ('symptoms', models.CharField(choices=[('Cough', 'Cough'), ('Fever', 'Fever'), ('Headache', 'Headache')], max_length=100)),
                ('family_diseases', models.CharField(choices=[('1', 'Diabetes'), ('2', "Huntington's chorea"), ('3', 'Cystic fibrosis')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('symptoms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Symptoms')),
            ],
        ),
    ]
