# Generated by Django 3.0.8 on 2020-08-04 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_diseases_quest_quest2_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='first_name',
            field=models.TextField(default='First name', max_length=25),
        ),
        migrations.AlterField(
            model_name='quest',
            name='last_name',
            field=models.TextField(default='Last name', max_length=30),
        ),
        migrations.AlterField(
            model_name='quest',
            name='pesel',
            field=models.CharField(blank=True, default='00000000000', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='sex',
            field=models.TextField(default='Female'),
        ),
        migrations.AlterField(
            model_name='quest2',
            name='drugs',
            field=models.CharField(default='No drugs', max_length=200),
        ),
        migrations.AlterField(
            model_name='quest2',
            name='family_diseases',
            field=models.CharField(default='No family diseases', max_length=200),
        ),
        migrations.AlterField(
            model_name='quest2',
            name='injury',
            field=models.CharField(default='No injuries', max_length=200),
        ),
        migrations.AlterField(
            model_name='quest2',
            name='symptoms',
            field=models.CharField(default='No symptoms', max_length=1000),
        ),

    ]
