# Generated by Django 3.0.3 on 2020-08-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20200804_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='user_id',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='quest2',
            name='user_id',
            field=models.IntegerField(default='0'),
        ),
    ]
